package DateApp;


/**
* DateApp/DateInterface_Tie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Arnis/Desktop/distributed systems/tut Ab/DateApp.idl
* 18 February 2015 11:37:31 o'clock GMT
*/

public class DateInterface_Tie extends _DateInterfaceImplBase
{

  // Constructors
  public DateInterface_Tie ()
  {
  }

  public DateInterface_Tie (DateApp.DateInterfaceOperations impl)
  {
    super ();
    _impl = impl;
  }

  public String getMasterDateMethod (String student)
  {
    return _impl.getMasterDateMethod(student);
  } // getMasterDateMethod

  private DateApp.DateInterfaceOperations _impl;

} // class DateInterface_Tie
