package DateApp;


/**
* DateApp/DateInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Arnis/Desktop/distributed systems/tut Ab/DateApp.idl
* 18 February 2015 11:37:31 o'clock GMT
*/

public interface DateInterface extends DateInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface DateInterface
