package HelloNaming;


/**
* HelloNaming/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Arnis/Desktop/distributed systems/tut Ba/HelloWorldName.idl
* 18 February 2015 19:29:12 o'clock GMT
*/

public interface HelloOperations 
{
  String sayHello ();
} // interface HelloOperations
